services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${VITE_APP_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      DATABASE_URL: ${POSTGRES_URL}?schema=public
      SERVER_PORT: ${SERVER_PORT}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      VITE_APP_NAME: ${VITE_APP_NAME}
      VITE_SERVER_BASE_URL: ${VITE_SERVER_BASE_URL}
      VITE_WEB_BASE_URL: ${VITE_WEB_BASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
    depends_on:
      - postgres
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - server
    ports:
      - "${WEB_PORT}:${WEB_PORT}"

volumes:
  postgres_data:
