services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: YN7144xT1RN6zpeGb1rh
      POSTGRES_DB: fullstackapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      DATABASE_URL: postgresql://app:YN7144xT1RN6zpeGb1rh@postgres:5432/fullstackapp?schema=public
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - server
    ports:
      - "4200:5173"

volumes:
  postgres_data:
